#
# Derived from
# https://github.com/steveno/ctags/blob/master/.travis.yml
#

language: c

env:
  - TEST_COMMAND="make check TRAVIS=1"
  - TEST_COMMAND="if [ \"$CC\" = 'gcc' ]; then make distclean; make -f mk_mingw.mak CC=i686-w64-mingw32-gcc; fi"
  - TEST_COMMAND="make fuzz VG=1 LANGUAGES=Ada,Ant,Asm,Asp,Awk,Basic"
  - TEST_COMMAND="make fuzz VG=1 LANGUAGES=BETA"

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq

install:
  - if [ $CC = 'gcc' ]; then sudo apt-get install -y binutils-mingw-w64-i686 gcc-mingw-w64-i686; fi
  - sudo apt-get install -y valgrind

# Build and run tests. Only with gcc cross compile
script:
  - autoreconf -f -i -v
  - ./configure
  - make -j2
  - bash -c "$TEST_COMMAND"

