jobs:
  build:
    docker:
      - image docker.io/centos:centos7

dependencies:
  override:
    - sudo yum -y install gcc automake autoconf git

test:
  pre:
    - bash ./autogen.sh
  override:
    - bash misc/circleci.sh CIRCLECI=1
