openapi: 3.0.0
info:
    title: test
    description: test
    version: '1.0'

servers:
  - url: http://example.com
    description: production
  - url: http://example2.com
    description: testing

paths:
    /sample/path:
        get:
            summary: simple handler
            responses: {}

    /sample/other/path:
        get:
            responses: {}
        post:
            summary: xxx
            responses: {}

components:
    schemas:
        NullableField:
            type: object
            properties: {}
        NullableFieldStringEnum:
            type: object
            properties: {}
    
    parameters:
        CustomHeader:
            in: header
            name: X-Custom-Header
            required: false
            schema:
                type: string
    
    responses:
        Response1:
            description: Payment Required
            content:
                application/json:
                    schema:
                        type: object
                        properties: {}
        Response2:
            description: smth 2
            content:
                application/json:
                    schema:
                        type: object
                        properties: {}
    examples:
        Example1:
            summary: xxx
            value: yyyyy
        Example2:
            b: xxxx
            summary: xxx
            value: yyyyy
    requestBodies:
        Body1:
            description: bla bla bla
            content:
                application/json:
                    schema:
                        type: string
        Body2:
            description: bla bla bla
            content:
                application/json:
                    schema:
                        type: integer
    headers:
        Header1:
            schema:
                type: string
        Header2:
            schema:
                type: string
    securitySchemes:
        SSchema1:
            type: http
            scheme: basic
        SSchema2:
            type: http
            scheme: basic
    links:
        Link1: {}
        Link2: {}
    callbacks:
        Callback1: {}
        Callback2: {}
    pathItems:
        PathItem1: {}
        PathItem2: {}



security:
  - type: apiKey
    name: api_key
    in: header
  - type: http
    scheme: basic

tags:
  - name: android_handler
    description: Handler for Android clients
  - name: ios_handler
    description: Handler for iOS clients

externalDocs:
    description: some docs
    url: http://example.com
