name: Create a weekly tag

on:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git config user.name  'Universal-ctags CI'
      - run: git config user.email 'Universal-ctags@users.noreply.github.com'

      - run: misc/git-tag-maybe.sh
