name: run units target on MSYS2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: windows-latest

    strategy:
      matrix:
        msystem: [MSYS]

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        install: git make automake1.16 autoconf

    - run: pacman -S --noconfirm gcc libiconv-devel pkg-config python dos2unix gdb

    - run: ln -s /usr/bin/automake-1.16 /usr/bin/automake
    - run: ln -s /usr/bin/aclocal-1.16  /usr/bin/aclocal
    
    - run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@v2

    - run: ./autogen.sh
    - run: ./configure --prefix=/usr
    - run: make V=1 CFLAGS="-g -O0"
    - run: make tmain V=1
