name: run units target on MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:

    strategy:
      matrix:
        os: [macos-11, macos-12]
        compiler: [gcc, clang]

    runs-on: ${{ matrix.os }}

    env:
      CC: ${{ matrix.compiler }}
      BUILDDIR: ${{ matrix.os }}-${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v2
    - name: update package information
      run: brew update
    - name: install tools and libraries
      run: |
        # python@3.11 symlink 2to3-3.11 to /usr/local/bin/2to3-3.11, but it already exists. so we need use --overwrite option when installing python@3.11, python@3.11 is depended by gdb.
        brew install --overwrite python@3.11
        brew install automake pkg-config bash libxml2 jansson libyaml gdb docutils pcre2
    - name: autogen.sh
      run: ./autogen.sh
    - name: report the version of cc
      run: ${{ matrix.compiler }} --version
    - name: report the version of make
      run: make --version
    - name: configure
      run: |
        mkdir -p ${{ matrix.os }}-"$CC"
        (
          cd $BUILDDIR
          ../configure --enable-debugging --enable-iconv
        )
    - name: make
      run: make -C $BUILDDIR -j2
    - name: report features
      run: |
        (
          cd $BUILDDIR
          ./ctags --list-features
        )
    - name: make check
      run: make -C $BUILDDIR check
    - name: make roundtrip
      run: make -C $BUILDDIR roundtrip
