name: run units target on macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:

    strategy:
      matrix:
        os: [macos-13, macos-12, macos-11]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    # temporarily disabled, because it always fails these days.
    #- run: brew update

    # NOTE: DO NOT try to install python3 package via brew, it has already been included in macos-xx runner images
    # https://github.com/actions/runner-images/blob/macos-13/20231002.1/images/macos/macos-13-Readme.md#python

    - run: brew install automake pkg-config jansson libyaml libxml2 pcre2

    - run: pip3 install docutils

    - run: cc --version
    - run: make --version

    - run: ./autogen.sh
    - run: ./configure --enable-debugging --enable-iconv
    - run: make -j2

    - run: ./ctags --version
    - run: ./ctags --list-features

    - run: make check
    - run: make roundtrip
    - run: make tmain
    - run: make units
