name: run units target on macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:

    strategy:
      matrix:
        os: [macos-13, macos-12, macos-11]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    # temporarily disabled, because it always fails these days.
    #- run: brew update

    # https://github.com/actions/runner-images/issues/6817
    - run: brew install --overwrite python@3.10 python@3.11
    - run: brew install automake pkg-config jansson libyaml docutils pcre2

    - run: cc --version
    - run: make --version

    - run: ./autogen.sh
    - run: ./configure --enable-debugging --enable-iconv
    - run: make -j2

    - run: ./ctags --version
    - run: ./ctags --list-features

    - run: make check
    - run: make roundtrip
    - run: make tmain
    - run: make units
